language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
services:
    - mongodb
matrix:
  fast_finish: true
# before_install:
# - travis_retry sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
# - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' |
#   sudo tee /etc/apt/sources.list.d/mongodb.list
# - travis_retry sudo apt-get update
# - travis_retry sudo apt-get install mongodb-org-server
install:
- sudo apt-get install python-dev python3-dev libopenjpeg-dev zlib1g-dev libjpeg-turbo8-dev
  libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev
  python-tk
- travis_retry pip install coveralls
- travis_retry pip install tox>=1.9
- travis_retry pip install "virtualenv<14.0.0"  # virtualenv>=14.0.0 has dropped Python 3.2 support (and pypy3 is based on py32)
- travis_retry tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/') -- -e test
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/') -- --cov-report= --cov=mongoengine_objectidmapfield
after_script: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
